### ISSUE TITLE
When an event is deleted the user gets the wrong notification on top of the screen

### ISSUE THREAD

**Issue by theitalianpreneur** [FocusPro-ai/focuspro#83]
![Image](https://user-images.githubusercontent.com/93001230/209654352-ba34019d-a587-4f0e-b569-323250cad08c.png)

**Comment by theitalianpreneur** [comment]
@AdityaPainuli this is an important one bro

**Comment by AdityaPainuli** [comment]
It's showing 'successfully deleted the task ' for me.
